# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/VivadoProject/AD9361_CONFIG_v1.2/AD9361_CONFIG_v1.2.srcs/sources_1/ip/dds_compiler_0/dds_compiler_0.xci
# IP: The module: 'dds_compiler_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/VivadoProject/AD9361_CONFIG_v1.2/AD9361_CONFIG_v1.2.srcs/sources_1/ip/dds_compiler_0/dds_compiler_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dds_compiler_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: E:/VivadoProject/AD9361_CONFIG_v1.2/AD9361_CONFIG_v1.2.srcs/sources_1/ip/dds_compiler_0/dds_compiler_0.xci
# IP: The module: 'dds_compiler_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/VivadoProject/AD9361_CONFIG_v1.2/AD9361_CONFIG_v1.2.srcs/sources_1/ip/dds_compiler_0/dds_compiler_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dds_compiler_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
