webtalk_init -webtalk_dir E:/VivadoProject/AD9361_TX_MSK/AD9361_TX_MSK.sim/sim_1/behav/xsim.dir/rom_test_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Jul 19 17:10:03 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2017.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "1846317" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "603a3fa3-7bc9-4e04-b1ad-e9fd483915f3" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "a2a0317a2ef245b7a7d9a95476944cb3" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "40" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 7 , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Service Pack 1  (build 7601)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i3-3240 CPU @ 3.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3392 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "4.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "6 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.11_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "8700_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2717918008 -regid "" -xml E:/VivadoProject/AD9361_TX_MSK/AD9361_TX_MSK.sim/sim_1/behav/xsim.dir/rom_test_behav/webtalk/usage_statistics_ext_xsim.xml -html E:/VivadoProject/AD9361_TX_MSK/AD9361_TX_MSK.sim/sim_1/behav/xsim.dir/rom_test_behav/webtalk/usage_statistics_ext_xsim.html -wdm E:/VivadoProject/AD9361_TX_MSK/AD9361_TX_MSK.sim/sim_1/behav/xsim.dir/rom_test_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
