# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/VivadoProject/AD9361_TX_MSK/AD9361_TX_MSK.srcs/sources_1/ip/qpath_generator/qpath_generator.xci
# IP: The module: 'qpath_generator' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/VivadoProject/AD9361_TX_MSK/AD9361_TX_MSK.srcs/sources_1/ip/qpath_generator/qpath_generator_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'qpath_generator'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: E:/VivadoProject/AD9361_TX_MSK/AD9361_TX_MSK.srcs/sources_1/ip/qpath_generator/qpath_generator.xci
# IP: The module: 'qpath_generator' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/VivadoProject/AD9361_TX_MSK/AD9361_TX_MSK.srcs/sources_1/ip/qpath_generator/qpath_generator_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'qpath_generator'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
